on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

name: rector

jobs:
  rector:
    uses: yiisoft/actions/.github/workflows/rector.yml@improve-rector
    secrets:
      token: ${{ secrets.YIISOFT_GITHUB_TOKEN }}
    permissions:
      contents: write
    with:
      repository: ${{ github.event.pull_request.head.repo.full_name }}
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.3']
